version: '3.8'

services:
  web:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile

    command:  sh -c "
                    chmod +x docker/entrypoint.sh &&
                    sh docker/entrypoint.sh"

    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db


volumes:
  postgres_data: