services:

#  postgresql container
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: nikitagrebnev
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: maddevs_task1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

# django-app container
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

# share code between host and container
volumes:
  postgres_data:

# enables communication between containers (web, db)
networks:
  app_network:
    driver: bridge