# Generated by Django 5.1.5 on 2025-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="test_field",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
