# Generated by Django 5.1.5 on 2025-01-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("doctor", "Доктор"), ("user", "Пользователь")], max_length=20
            ),
        ),
    ]
